[project]
name = "api"
version = "0.1.0"
description = "api for the abstractabstraction site"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.27",
    "fastapi[all]>=0.115.12",
    "mangum>=0.19.0",
    "uvicorn>=0.34.2",
]
